<?php

// Data functions (insert, update, delete, form) for table cikgu

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function cikgu_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('cikgu');
	if(!$arrPerm[1]){
		return false;
	}

	$data['nama'] = makeSafe($_REQUEST['nama']);
		if($data['nama'] == empty_lookup_value){ $data['nama'] = ''; }
	$data['email'] = makeSafe($_REQUEST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['phone']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['alamat'] = makeSafe($_REQUEST['alamat']);
		if($data['alamat'] == empty_lookup_value){ $data['alamat'] = ''; }
	$data['ditambahOleh'] = makeSafe($_REQUEST['ditambahOleh']);
		if($data['ditambahOleh'] == empty_lookup_value){ $data['ditambahOleh'] = ''; }
	$data['adminID'] = makeSafe($_REQUEST['adminID']);
		if($data['adminID'] == empty_lookup_value){ $data['adminID'] = ''; }

	// hook: cikgu_before_insert
	if(function_exists('cikgu_before_insert')){
		$args=array();
		if(!cikgu_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `cikgu` set       `nama`=' . (($data['nama'] !== '' && $data['nama'] !== NULL) ? "'{$data['nama']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `alamat`=' . (($data['alamat'] !== '' && $data['alamat'] !== NULL) ? "'{$data['alamat']}'" : 'NULL') . ', `ditambahOleh`=' . (($data['ditambahOleh'] !== '' && $data['ditambahOleh'] !== NULL) ? "'{$data['ditambahOleh']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"cikgu_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic adminID
	if($_REQUEST['filterer_adminID']){
		sql("update `cikgu` set `adminID`='" . makeSafe($_REQUEST['filterer_adminID']) . "' where `cikguID`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: cikgu_after_insert
	if(function_exists('cikgu_after_insert')){
		$res = sql("select * from `cikgu` where `cikguID`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!cikgu_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('cikgu', $recID, getLoggedMemberID());

	return $recID;
}

function cikgu_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('cikgu');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='cikgu' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='cikgu' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: cikgu_before_delete
	if(function_exists('cikgu_before_delete')){
		$args=array();
		if(!cikgu_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `cikgu` where `cikguID`='$selected_id'", $eo);

	// hook: cikgu_after_delete
	if(function_exists('cikgu_after_delete')){
		$args=array();
		cikgu_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='cikgu' and pkValue='$selected_id'", $eo);
}

function cikgu_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('cikgu');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='cikgu' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='cikgu' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['nama'] = makeSafe($_REQUEST['nama']);
		if($data['nama'] == empty_lookup_value){ $data['nama'] = ''; }
	$data['email'] = makeSafe($_REQUEST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['phone']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['alamat'] = makeSafe($_REQUEST['alamat']);
		if($data['alamat'] == empty_lookup_value){ $data['alamat'] = ''; }
	$data['ditambahOleh'] = makeSafe($_REQUEST['ditambahOleh']);
		if($data['ditambahOleh'] == empty_lookup_value){ $data['ditambahOleh'] = ''; }
	$data['adminID'] = makeSafe($_REQUEST['adminID']);
		if($data['adminID'] == empty_lookup_value){ $data['adminID'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: cikgu_before_update
	if(function_exists('cikgu_before_update')){
		$args=array();
		if(!cikgu_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `cikgu` set       `nama`=' . (($data['nama'] !== '' && $data['nama'] !== NULL) ? "'{$data['nama']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `alamat`=' . (($data['alamat'] !== '' && $data['alamat'] !== NULL) ? "'{$data['alamat']}'" : 'NULL') . ', `ditambahOleh`=' . (($data['ditambahOleh'] !== '' && $data['ditambahOleh'] !== NULL) ? "'{$data['ditambahOleh']}'" : 'NULL') . " where `cikguID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="cikgu_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: cikgu_after_update
	if(function_exists('cikgu_after_update')){
		$res = sql("SELECT * FROM `cikgu` WHERE `cikguID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['cikguID'];
		$args = array();
		if(!cikgu_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='cikgu' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function cikgu_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('cikgu');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_ditambahOleh = thisOr(undo_magic_quotes($_REQUEST['filterer_ditambahOleh']), '');
	$filterer_adminID = thisOr(undo_magic_quotes($_REQUEST['filterer_adminID']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: ditambahOleh
	$combo_ditambahOleh = new DataCombo;
	// combobox: adminID
	$combo_adminID = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='cikgu' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='cikgu' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `cikgu` where `cikguID`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'cikgu_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_ditambahOleh->SelectedData = $row['ditambahOleh'];
		$combo_adminID->SelectedData = $row['adminID'];
	}else{
		$combo_ditambahOleh->SelectedData = $filterer_ditambahOleh;
		$combo_adminID->SelectedData = $filterer_adminID;
	}
	$combo_ditambahOleh->HTML = '<span id="ditambahOleh-container' . $rnd1 . '"></span><input type="hidden" name="ditambahOleh" id="ditambahOleh' . $rnd1 . '" value="' . html_attr($combo_ditambahOleh->SelectedData) . '">';
	$combo_ditambahOleh->MatchText = '<span id="ditambahOleh-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ditambahOleh" id="ditambahOleh' . $rnd1 . '" value="' . html_attr($combo_ditambahOleh->SelectedData) . '">';
	$combo_adminID->HTML = '<span id="adminID-container' . $rnd1 . '"></span><input type="hidden" name="adminID" id="adminID' . $rnd1 . '" value="' . html_attr($combo_adminID->SelectedData) . '">';
	$combo_adminID->MatchText = '<span id="adminID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="adminID" id="adminID' . $rnd1 . '" value="' . html_attr($combo_adminID->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_ditambahOleh__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ditambahOleh'] : $filterer_ditambahOleh); ?>"};
		AppGini.current_adminID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['adminID'] : $filterer_adminID); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(ditambahOleh_reload__RAND__) == 'function') ditambahOleh_reload__RAND__();
				if(typeof(adminID_reload__RAND__) == 'function') adminID_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function ditambahOleh_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#ditambahOleh-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_ditambahOleh__RAND__.value, t: 'cikgu', f: 'ditambahOleh' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ditambahOleh"]').val(resp.results[0].id);
							$j('[id=ditambahOleh-container-readonly__RAND__]').html('<span id="ditambahOleh-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


							if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'cikgu', f: 'ditambahOleh' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_ditambahOleh__RAND__.value = e.added.id;
				AppGini.current_ditambahOleh__RAND__.text = e.added.text;
				$j('[name="ditambahOleh"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


				if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
			});

			if(!$j("#ditambahOleh-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ditambahOleh__RAND__.value, t: 'cikgu', f: 'ditambahOleh' },
					success: function(resp){
						$j('[name="ditambahOleh"]').val(resp.results[0].id);
						$j('[id=ditambahOleh-container-readonly__RAND__]').html('<span id="ditambahOleh-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

						if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ditambahOleh__RAND__.value, t: 'cikgu', f: 'ditambahOleh' },
				success: function(resp){
					$j('[id=ditambahOleh-container__RAND__], [id=ditambahOleh-container-readonly__RAND__]').html('<span id="ditambahOleh-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

					if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function adminID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#adminID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_adminID__RAND__.value, t: 'cikgu', f: 'adminID' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="adminID"]').val(resp.results[0].id);
							$j('[id=adminID-container-readonly__RAND__]').html('<span id="adminID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


							if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'cikgu', f: 'adminID' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_adminID__RAND__.value = e.added.id;
				AppGini.current_adminID__RAND__.text = e.added.text;
				$j('[name="adminID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


				if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
			});

			if(!$j("#adminID-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_adminID__RAND__.value, t: 'cikgu', f: 'adminID' },
					success: function(resp){
						$j('[name="adminID"]').val(resp.results[0].id);
						$j('[id=adminID-container-readonly__RAND__]').html('<span id="adminID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

						if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_adminID__RAND__.value, t: 'cikgu', f: 'adminID' },
				success: function(resp){
					$j('[id=adminID-container__RAND__], [id=adminID-container-readonly__RAND__]').html('<span id="adminID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

					if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/cikgu_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/cikgu_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Cikgu details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return cikgu_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return cikgu_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return cikgu_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#nama').replaceWith('<div class=\"form-control-static\" id=\"nama\">' + (jQuery('#nama').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email, #email-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#phone').replaceWith('<div class=\"form-control-static\" id=\"phone\">' + (jQuery('#phone').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#alamat').replaceWith('<div class=\"form-control-static\" id=\"alamat\">' + (jQuery('#alamat').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ditambahOleh').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ditambahOleh_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(ditambahOleh)%%>', $combo_ditambahOleh->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ditambahOleh)%%>', $combo_ditambahOleh->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ditambahOleh)%%>', urlencode($combo_ditambahOleh->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(adminID)%%>', $combo_adminID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(adminID)%%>', $combo_adminID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(adminID)%%>', urlencode($combo_adminID->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'ditambahOleh' => array('admin', 'DitambahOleh'), 'adminID' => array('admin', 'AdminID'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(cikguID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nama)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(phone)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(alamat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ditambahOleh)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(adminID)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cikguID)%%>', safe_html($urow['cikguID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cikguID)%%>', html_attr($row['cikguID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cikguID)%%>', urlencode($urow['cikguID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nama)%%>', safe_html($urow['nama']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nama)%%>', html_attr($row['nama']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama)%%>', urlencode($urow['nama']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(phone)%%>', safe_html($urow['phone']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(phone)%%>', html_attr($row['phone']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone)%%>', urlencode($urow['phone']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(alamat)%%>', safe_html($urow['alamat']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(alamat)%%>', html_attr($row['alamat']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(alamat)%%>', urlencode($urow['alamat']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ditambahOleh)%%>', safe_html($urow['ditambahOleh']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ditambahOleh)%%>', html_attr($row['ditambahOleh']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ditambahOleh)%%>', urlencode($urow['ditambahOleh']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(adminID)%%>', safe_html($urow['adminID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(adminID)%%>', html_attr($row['adminID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adminID)%%>', urlencode($urow['adminID']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(cikguID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cikguID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nama)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(phone)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(alamat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(alamat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ditambahOleh)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ditambahOleh)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(adminID)%%>', ( $_REQUEST['FilterField'][1]=='7' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_adminID->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adminID)%%>', urlencode( $_REQUEST['FilterField'][1]=='7' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_adminID->SelectedData : ''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('emailEdit')){ document.getElementById('emailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('cikgu');
	if($selected_id){
		$jdata = get_joined_record('cikgu', $selected_id);
		if($jdata === false) $jdata = get_defaults('cikgu');
		$rdata = $row;
	}
	$templateCode .= loadView('cikgu-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: cikgu_dv
	if(function_exists('cikgu_dv')){
		$args=array();
		cikgu_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>