<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/cikgu.php");
	include("$currDir/cikgu_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('cikgu');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "cikgu";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`cikgu`.`cikguID`" => "cikguID",
		"`cikgu`.`nama`" => "nama",
		"`cikgu`.`email`" => "email",
		"`cikgu`.`phone`" => "phone",
		"`cikgu`.`alamat`" => "alamat",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* DitambahOleh */" => "ditambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "adminID"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`cikgu`.`cikguID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`admin1`.`nama`',
		7 => '`admin2`.`nama`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`cikgu`.`cikguID`" => "cikguID",
		"`cikgu`.`nama`" => "nama",
		"`cikgu`.`email`" => "email",
		"`cikgu`.`phone`" => "phone",
		"`cikgu`.`alamat`" => "alamat",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* DitambahOleh */" => "ditambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "adminID"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`cikgu`.`cikguID`" => "CikguID",
		"`cikgu`.`nama`" => "Nama",
		"`cikgu`.`email`" => "Email",
		"`cikgu`.`phone`" => "Phone",
		"`cikgu`.`alamat`" => "Alamat",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* DitambahOleh */" => "DitambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "AdminID"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`cikgu`.`cikguID`" => "cikguID",
		"`cikgu`.`nama`" => "nama",
		"`cikgu`.`email`" => "email",
		"`cikgu`.`phone`" => "phone",
		"`cikgu`.`alamat`" => "alamat",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* DitambahOleh */" => "ditambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "adminID"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'ditambahOleh' => 'DitambahOleh', 'adminID' => 'AdminID');

	$x->QueryFrom = "`cikgu` LEFT JOIN `admin` as admin1 ON `admin1`.`adminID`=`cikgu`.`ditambahOleh` LEFT JOIN `admin` as admin2 ON `admin2`.`adminID`=`cikgu`.`adminID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "cikgu_view.php";
	$x->RedirectAfterInsert = "cikgu_view.php?SelectedID=#ID#";
	$x->TableTitle = "Cikgu";
	$x->TableIcon = "resources/table_icons/client_account_template.png";
	$x->PrimaryKey = "`cikgu`.`cikguID`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Nama", "Email", "Phone", "Alamat");
	$x->ColFieldName = array('nama', 'email', 'phone', 'alamat');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/cikgu_templateTV.html';
	$x->SelectedTemplate = 'templates/cikgu_templateTVS.html';
	$x->TemplateDV = 'templates/cikgu_templateDV.html';
	$x->TemplateDVP = 'templates/cikgu_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `cikgu`.`cikguID`=membership_userrecords.pkValue and membership_userrecords.tableName='cikgu' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `cikgu`.`cikguID`=membership_userrecords.pkValue and membership_userrecords.tableName='cikgu' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`cikgu`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: cikgu_init
	$render=TRUE;
	if(function_exists('cikgu_init')){
		$args=array();
		$render=cikgu_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: cikgu_header
	$headerCode='';
	if(function_exists('cikgu_header')){
		$args=array();
		$headerCode=cikgu_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: cikgu_footer
	$footerCode='';
	if(function_exists('cikgu_footer')){
		$args=array();
		$footerCode=cikgu_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>