<?php

// Data functions (insert, update, delete, form) for table pelajar

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function pelajar_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('pelajar');
	if(!$arrPerm[1]){
		return false;
	}

	$data['nama'] = makeSafe($_REQUEST['nama']);
		if($data['nama'] == empty_lookup_value){ $data['nama'] = ''; }
	$data['umur'] = makeSafe($_REQUEST['umur']);
		if($data['umur'] == empty_lookup_value){ $data['umur'] = ''; }
	$data['alamat'] = makeSafe($_REQUEST['alamat']);
		if($data['alamat'] == empty_lookup_value){ $data['alamat'] = ''; }
	$data['subjek'] = makeSafe($_REQUEST['subjek']);
		if($data['subjek'] == empty_lookup_value){ $data['subjek'] = ''; }
	$data['ditambahOleh'] = makeSafe($_REQUEST['ditambahOleh']);
		if($data['ditambahOleh'] == empty_lookup_value){ $data['ditambahOleh'] = ''; }
	$data['adminID'] = makeSafe($_REQUEST['adminID']);
		if($data['adminID'] == empty_lookup_value){ $data['adminID'] = ''; }
	$data['subjekID'] = makeSafe($_REQUEST['subjekID']);
		if($data['subjekID'] == empty_lookup_value){ $data['subjekID'] = ''; }
	if($data['statusYuran'] == '') $data['statusYuran'] = "Belum Bayar";

	// hook: pelajar_before_insert
	if(function_exists('pelajar_before_insert')){
		$args=array();
		if(!pelajar_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `pelajar` set       `nama`=' . (($data['nama'] !== '' && $data['nama'] !== NULL) ? "'{$data['nama']}'" : 'NULL') . ', `umur`=' . (($data['umur'] !== '' && $data['umur'] !== NULL) ? "'{$data['umur']}'" : 'NULL') . ', `alamat`=' . (($data['alamat'] !== '' && $data['alamat'] !== NULL) ? "'{$data['alamat']}'" : 'NULL') . ', `subjek`=' . (($data['subjek'] !== '' && $data['subjek'] !== NULL) ? "'{$data['subjek']}'" : 'NULL') . ', `ditambahOleh`=' . (($data['ditambahOleh'] !== '' && $data['ditambahOleh'] !== NULL) ? "'{$data['ditambahOleh']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"pelajar_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic adminID
	if($_REQUEST['filterer_adminID']){
		sql("update `pelajar` set `adminID`='" . makeSafe($_REQUEST['filterer_adminID']) . "' where `pelajarID`='" . makeSafe($recID, false) . "'", $eo);
	}

	// automatic subjekID
	if($_REQUEST['filterer_subjekID']){
		sql("update `pelajar` set `subjekID`='" . makeSafe($_REQUEST['filterer_subjekID']) . "' where `pelajarID`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: pelajar_after_insert
	if(function_exists('pelajar_after_insert')){
		$res = sql("select * from `pelajar` where `pelajarID`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!pelajar_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('pelajar', $recID, getLoggedMemberID());

	return $recID;
}

function pelajar_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('pelajar');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='pelajar' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='pelajar' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: pelajar_before_delete
	if(function_exists('pelajar_before_delete')){
		$args=array();
		if(!pelajar_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `pelajar` where `pelajarID`='$selected_id'", $eo);

	// hook: pelajar_after_delete
	if(function_exists('pelajar_after_delete')){
		$args=array();
		pelajar_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='pelajar' and pkValue='$selected_id'", $eo);
}

function pelajar_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('pelajar');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='pelajar' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='pelajar' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['nama'] = makeSafe($_REQUEST['nama']);
		if($data['nama'] == empty_lookup_value){ $data['nama'] = ''; }
	$data['umur'] = makeSafe($_REQUEST['umur']);
		if($data['umur'] == empty_lookup_value){ $data['umur'] = ''; }
	$data['alamat'] = makeSafe($_REQUEST['alamat']);
		if($data['alamat'] == empty_lookup_value){ $data['alamat'] = ''; }
	$data['subjek'] = makeSafe($_REQUEST['subjek']);
		if($data['subjek'] == empty_lookup_value){ $data['subjek'] = ''; }
	$data['ditambahOleh'] = makeSafe($_REQUEST['ditambahOleh']);
		if($data['ditambahOleh'] == empty_lookup_value){ $data['ditambahOleh'] = ''; }
	$data['adminID'] = makeSafe($_REQUEST['adminID']);
		if($data['adminID'] == empty_lookup_value){ $data['adminID'] = ''; }
	$data['subjekID'] = makeSafe($_REQUEST['subjekID']);
		if($data['subjekID'] == empty_lookup_value){ $data['subjekID'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: pelajar_before_update
	if(function_exists('pelajar_before_update')){
		$args=array();
		if(!pelajar_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `pelajar` set       `nama`=' . (($data['nama'] !== '' && $data['nama'] !== NULL) ? "'{$data['nama']}'" : 'NULL') . ', `umur`=' . (($data['umur'] !== '' && $data['umur'] !== NULL) ? "'{$data['umur']}'" : 'NULL') . ', `alamat`=' . (($data['alamat'] !== '' && $data['alamat'] !== NULL) ? "'{$data['alamat']}'" : 'NULL') . ', `subjek`=' . (($data['subjek'] !== '' && $data['subjek'] !== NULL) ? "'{$data['subjek']}'" : 'NULL') . ', `ditambahOleh`=' . (($data['ditambahOleh'] !== '' && $data['ditambahOleh'] !== NULL) ? "'{$data['ditambahOleh']}'" : 'NULL') . " where `pelajarID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="pelajar_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: pelajar_after_update
	if(function_exists('pelajar_after_update')){
		$res = sql("SELECT * FROM `pelajar` WHERE `pelajarID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['pelajarID'];
		$args = array();
		if(!pelajar_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='pelajar' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function pelajar_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('pelajar');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_subjek = thisOr(undo_magic_quotes($_REQUEST['filterer_subjek']), '');
	$filterer_ditambahOleh = thisOr(undo_magic_quotes($_REQUEST['filterer_ditambahOleh']), '');
	$filterer_adminID = thisOr(undo_magic_quotes($_REQUEST['filterer_adminID']), '');
	$filterer_subjekID = thisOr(undo_magic_quotes($_REQUEST['filterer_subjekID']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: subjek
	$combo_subjek = new DataCombo;
	// combobox: ditambahOleh
	$combo_ditambahOleh = new DataCombo;
	// combobox: adminID
	$combo_adminID = new DataCombo;
	// combobox: subjekID
	$combo_subjekID = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='pelajar' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='pelajar' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `pelajar` where `pelajarID`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'pelajar_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_subjek->SelectedData = $row['subjek'];
		$combo_ditambahOleh->SelectedData = $row['ditambahOleh'];
		$combo_adminID->SelectedData = $row['adminID'];
		$combo_subjekID->SelectedData = $row['subjekID'];
	}else{
		$combo_subjek->SelectedData = $filterer_subjek;
		$combo_ditambahOleh->SelectedData = $filterer_ditambahOleh;
		$combo_adminID->SelectedData = $filterer_adminID;
		$combo_subjekID->SelectedData = $filterer_subjekID;
	}
	$combo_subjek->HTML = '<span id="subjek-container' . $rnd1 . '"></span><input type="hidden" name="subjek" id="subjek' . $rnd1 . '" value="' . html_attr($combo_subjek->SelectedData) . '">';
	$combo_subjek->MatchText = '<span id="subjek-container-readonly' . $rnd1 . '"></span><input type="hidden" name="subjek" id="subjek' . $rnd1 . '" value="' . html_attr($combo_subjek->SelectedData) . '">';
	$combo_ditambahOleh->HTML = '<span id="ditambahOleh-container' . $rnd1 . '"></span><input type="hidden" name="ditambahOleh" id="ditambahOleh' . $rnd1 . '" value="' . html_attr($combo_ditambahOleh->SelectedData) . '">';
	$combo_ditambahOleh->MatchText = '<span id="ditambahOleh-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ditambahOleh" id="ditambahOleh' . $rnd1 . '" value="' . html_attr($combo_ditambahOleh->SelectedData) . '">';
	$combo_adminID->HTML = '<span id="adminID-container' . $rnd1 . '"></span><input type="hidden" name="adminID" id="adminID' . $rnd1 . '" value="' . html_attr($combo_adminID->SelectedData) . '">';
	$combo_adminID->MatchText = '<span id="adminID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="adminID" id="adminID' . $rnd1 . '" value="' . html_attr($combo_adminID->SelectedData) . '">';
	$combo_subjekID->HTML = '<span id="subjekID-container' . $rnd1 . '"></span><input type="hidden" name="subjekID" id="subjekID' . $rnd1 . '" value="' . html_attr($combo_subjekID->SelectedData) . '">';
	$combo_subjekID->MatchText = '<span id="subjekID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="subjekID" id="subjekID' . $rnd1 . '" value="' . html_attr($combo_subjekID->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_subjek__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['subjek'] : $filterer_subjek); ?>"};
		AppGini.current_ditambahOleh__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ditambahOleh'] : $filterer_ditambahOleh); ?>"};
		AppGini.current_adminID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['adminID'] : $filterer_adminID); ?>"};
		AppGini.current_subjekID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['subjekID'] : $filterer_subjekID); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(subjek_reload__RAND__) == 'function') subjek_reload__RAND__();
				if(typeof(ditambahOleh_reload__RAND__) == 'function') ditambahOleh_reload__RAND__();
				if(typeof(adminID_reload__RAND__) == 'function') adminID_reload__RAND__();
				if(typeof(subjekID_reload__RAND__) == 'function') subjekID_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function subjek_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#subjek-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_subjek__RAND__.value, t: 'pelajar', f: 'subjek' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="subjek"]').val(resp.results[0].id);
							$j('[id=subjek-container-readonly__RAND__]').html('<span id="subjek-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }


							if(typeof(subjek_update_autofills__RAND__) == 'function') subjek_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'pelajar', f: 'subjek' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_subjek__RAND__.value = e.added.id;
				AppGini.current_subjek__RAND__.text = e.added.text;
				$j('[name="subjek"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }


				if(typeof(subjek_update_autofills__RAND__) == 'function') subjek_update_autofills__RAND__();
			});

			if(!$j("#subjek-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_subjek__RAND__.value, t: 'pelajar', f: 'subjek' },
					success: function(resp){
						$j('[name="subjek"]').val(resp.results[0].id);
						$j('[id=subjek-container-readonly__RAND__]').html('<span id="subjek-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }

						if(typeof(subjek_update_autofills__RAND__) == 'function') subjek_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_subjek__RAND__.value, t: 'pelajar', f: 'subjek' },
				success: function(resp){
					$j('[id=subjek-container__RAND__], [id=subjek-container-readonly__RAND__]').html('<span id="subjek-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }

					if(typeof(subjek_update_autofills__RAND__) == 'function') subjek_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function ditambahOleh_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#ditambahOleh-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_ditambahOleh__RAND__.value, t: 'pelajar', f: 'ditambahOleh' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ditambahOleh"]').val(resp.results[0].id);
							$j('[id=ditambahOleh-container-readonly__RAND__]').html('<span id="ditambahOleh-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


							if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'pelajar', f: 'ditambahOleh' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_ditambahOleh__RAND__.value = e.added.id;
				AppGini.current_ditambahOleh__RAND__.text = e.added.text;
				$j('[name="ditambahOleh"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


				if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
			});

			if(!$j("#ditambahOleh-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ditambahOleh__RAND__.value, t: 'pelajar', f: 'ditambahOleh' },
					success: function(resp){
						$j('[name="ditambahOleh"]').val(resp.results[0].id);
						$j('[id=ditambahOleh-container-readonly__RAND__]').html('<span id="ditambahOleh-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

						if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ditambahOleh__RAND__.value, t: 'pelajar', f: 'ditambahOleh' },
				success: function(resp){
					$j('[id=ditambahOleh-container__RAND__], [id=ditambahOleh-container-readonly__RAND__]').html('<span id="ditambahOleh-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

					if(typeof(ditambahOleh_update_autofills__RAND__) == 'function') ditambahOleh_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function adminID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#adminID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_adminID__RAND__.value, t: 'pelajar', f: 'adminID' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="adminID"]').val(resp.results[0].id);
							$j('[id=adminID-container-readonly__RAND__]').html('<span id="adminID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


							if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'pelajar', f: 'adminID' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_adminID__RAND__.value = e.added.id;
				AppGini.current_adminID__RAND__.text = e.added.text;
				$j('[name="adminID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }


				if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
			});

			if(!$j("#adminID-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_adminID__RAND__.value, t: 'pelajar', f: 'adminID' },
					success: function(resp){
						$j('[name="adminID"]').val(resp.results[0].id);
						$j('[id=adminID-container-readonly__RAND__]').html('<span id="adminID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

						if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_adminID__RAND__.value, t: 'pelajar', f: 'adminID' },
				success: function(resp){
					$j('[id=adminID-container__RAND__], [id=adminID-container-readonly__RAND__]').html('<span id="adminID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=admin_view_parent]').hide(); }else{ $j('.btn[id=admin_view_parent]').show(); }

					if(typeof(adminID_update_autofills__RAND__) == 'function') adminID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function subjekID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#subjekID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_subjekID__RAND__.value, t: 'pelajar', f: 'subjekID' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="subjekID"]').val(resp.results[0].id);
							$j('[id=subjekID-container-readonly__RAND__]').html('<span id="subjekID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }


							if(typeof(subjekID_update_autofills__RAND__) == 'function') subjekID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'pelajar', f: 'subjekID' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_subjekID__RAND__.value = e.added.id;
				AppGini.current_subjekID__RAND__.text = e.added.text;
				$j('[name="subjekID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }


				if(typeof(subjekID_update_autofills__RAND__) == 'function') subjekID_update_autofills__RAND__();
			});

			if(!$j("#subjekID-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_subjekID__RAND__.value, t: 'pelajar', f: 'subjekID' },
					success: function(resp){
						$j('[name="subjekID"]').val(resp.results[0].id);
						$j('[id=subjekID-container-readonly__RAND__]').html('<span id="subjekID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }

						if(typeof(subjekID_update_autofills__RAND__) == 'function') subjekID_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_subjekID__RAND__.value, t: 'pelajar', f: 'subjekID' },
				success: function(resp){
					$j('[id=subjekID-container__RAND__], [id=subjekID-container-readonly__RAND__]').html('<span id="subjekID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Subjek_view_parent]').hide(); }else{ $j('.btn[id=Subjek_view_parent]').show(); }

					if(typeof(subjekID_update_autofills__RAND__) == 'function') subjekID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/pelajar_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/pelajar_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Pelajar details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return pelajar_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return pelajar_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return pelajar_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#nama').replaceWith('<div class=\"form-control-static\" id=\"nama\">' + (jQuery('#nama').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#umur').replaceWith('<div class=\"form-control-static\" id=\"umur\">' + (jQuery('#umur').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#alamat').replaceWith('<div class=\"form-control-static\" id=\"alamat\">' + (jQuery('#alamat').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#subjek').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#subjek_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#s2id_subjek').remove();\n";
		$jsReadOnly .= "\tjQuery('#ditambahOleh').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ditambahOleh_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(subjek)%%>', $combo_subjek->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(subjek)%%>', $combo_subjek->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(subjek)%%>', urlencode($combo_subjek->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(ditambahOleh)%%>', $combo_ditambahOleh->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ditambahOleh)%%>', $combo_ditambahOleh->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ditambahOleh)%%>', urlencode($combo_ditambahOleh->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(adminID)%%>', $combo_adminID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(adminID)%%>', $combo_adminID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(adminID)%%>', urlencode($combo_adminID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(subjekID)%%>', $combo_subjekID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(subjekID)%%>', $combo_subjekID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(subjekID)%%>', urlencode($combo_subjekID->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'subjek' => array('Subjek', 'Subjek'), 'ditambahOleh' => array('admin', 'Ditambah Oleh'), 'adminID' => array('admin', 'AdminID'), 'subjekID' => array('Subjek', 'SubjekID'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(pelajarID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nama)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(umur)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(alamat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subjek)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(statusYuran)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ditambahOleh)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(adminID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subjekID)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pelajarID)%%>', safe_html($urow['pelajarID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pelajarID)%%>', html_attr($row['pelajarID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pelajarID)%%>', urlencode($urow['pelajarID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nama)%%>', safe_html($urow['nama']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nama)%%>', html_attr($row['nama']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama)%%>', urlencode($urow['nama']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(umur)%%>', safe_html($urow['umur']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(umur)%%>', html_attr($row['umur']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(umur)%%>', urlencode($urow['umur']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(alamat)%%>', safe_html($urow['alamat']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(alamat)%%>', html_attr($row['alamat']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(alamat)%%>', urlencode($urow['alamat']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subjek)%%>', safe_html($urow['subjek']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subjek)%%>', html_attr($row['subjek']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subjek)%%>', urlencode($urow['subjek']), $templateCode);
		$templateCode = str_replace('<%%VALUE(statusYuran)%%>', safe_html($urow['statusYuran']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(statusYuran)%%>', urlencode($urow['statusYuran']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ditambahOleh)%%>', safe_html($urow['ditambahOleh']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ditambahOleh)%%>', html_attr($row['ditambahOleh']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ditambahOleh)%%>', urlencode($urow['ditambahOleh']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(adminID)%%>', safe_html($urow['adminID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(adminID)%%>', html_attr($row['adminID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adminID)%%>', urlencode($urow['adminID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subjekID)%%>', safe_html($urow['subjekID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subjekID)%%>', html_attr($row['subjekID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subjekID)%%>', urlencode($urow['subjekID']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(pelajarID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pelajarID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nama)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nama)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(umur)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(umur)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(alamat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(alamat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subjek)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subjek)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(statusYuran)%%>', 'Belum Bayar', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(statusYuran)%%>', urlencode('Belum Bayar'), $templateCode);
		$templateCode = str_replace('<%%VALUE(ditambahOleh)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ditambahOleh)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(adminID)%%>', ( $_REQUEST['FilterField'][1]=='8' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_adminID->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adminID)%%>', urlencode( $_REQUEST['FilterField'][1]=='8' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_adminID->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subjekID)%%>', ( $_REQUEST['FilterField'][1]=='9' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_subjekID->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subjekID)%%>', urlencode( $_REQUEST['FilterField'][1]=='9' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_subjekID->SelectedData : ''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('pelajar');
	if($selected_id){
		$jdata = get_joined_record('pelajar', $selected_id);
		if($jdata === false) $jdata = get_defaults('pelajar');
		$rdata = $row;
	}
	$templateCode .= loadView('pelajar-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: pelajar_dv
	if(function_exists('pelajar_dv')){
		$args=array();
		pelajar_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>