<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/pelajar.php");
	include("$currDir/pelajar_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('pelajar');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "pelajar";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`pelajar`.`pelajarID`" => "pelajarID",
		"`pelajar`.`nama`" => "nama",
		"`pelajar`.`umur`" => "umur",
		"`pelajar`.`alamat`" => "alamat",
		"IF(    CHAR_LENGTH(`Subjek1`.`subjekKode`) || CHAR_LENGTH(`Subjek1`.`subjekNama`), CONCAT_WS('',   `Subjek1`.`subjekKode`, ' - ', `Subjek1`.`subjekNama`), '') /* Subjek */" => "subjek",
		"`pelajar`.`statusYuran`" => "statusYuran",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* Ditambah Oleh */" => "ditambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "adminID",
		"IF(    CHAR_LENGTH(`Subjek2`.`subjekNama`), CONCAT_WS('',   `Subjek2`.`subjekNama`), '') /* SubjekID */" => "subjekID"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`pelajar`.`pelajarID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`admin1`.`nama`',
		8 => '`admin2`.`nama`',
		9 => '`Subjek2`.`subjekNama`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`pelajar`.`pelajarID`" => "pelajarID",
		"`pelajar`.`nama`" => "nama",
		"`pelajar`.`umur`" => "umur",
		"`pelajar`.`alamat`" => "alamat",
		"IF(    CHAR_LENGTH(`Subjek1`.`subjekKode`) || CHAR_LENGTH(`Subjek1`.`subjekNama`), CONCAT_WS('',   `Subjek1`.`subjekKode`, ' - ', `Subjek1`.`subjekNama`), '') /* Subjek */" => "subjek",
		"`pelajar`.`statusYuran`" => "statusYuran",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* Ditambah Oleh */" => "ditambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "adminID",
		"IF(    CHAR_LENGTH(`Subjek2`.`subjekNama`), CONCAT_WS('',   `Subjek2`.`subjekNama`), '') /* SubjekID */" => "subjekID"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`pelajar`.`pelajarID`" => "PelajarID",
		"`pelajar`.`nama`" => "Nama",
		"`pelajar`.`umur`" => "Umur",
		"`pelajar`.`alamat`" => "Alamat",
		"IF(    CHAR_LENGTH(`Subjek1`.`subjekKode`) || CHAR_LENGTH(`Subjek1`.`subjekNama`), CONCAT_WS('',   `Subjek1`.`subjekKode`, ' - ', `Subjek1`.`subjekNama`), '') /* Subjek */" => "Subjek",
		"`pelajar`.`statusYuran`" => "Status Yuran",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* Ditambah Oleh */" => "Ditambah Oleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "AdminID",
		"IF(    CHAR_LENGTH(`Subjek2`.`subjekNama`), CONCAT_WS('',   `Subjek2`.`subjekNama`), '') /* SubjekID */" => "SubjekID"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`pelajar`.`pelajarID`" => "pelajarID",
		"`pelajar`.`nama`" => "nama",
		"`pelajar`.`umur`" => "umur",
		"`pelajar`.`alamat`" => "alamat",
		"IF(    CHAR_LENGTH(`Subjek1`.`subjekKode`) || CHAR_LENGTH(`Subjek1`.`subjekNama`), CONCAT_WS('',   `Subjek1`.`subjekKode`, ' - ', `Subjek1`.`subjekNama`), '') /* Subjek */" => "subjek",
		"`pelajar`.`statusYuran`" => "statusYuran",
		"IF(    CHAR_LENGTH(`admin1`.`nama`), CONCAT_WS('',   `admin1`.`nama`), '') /* Ditambah Oleh */" => "ditambahOleh",
		"IF(    CHAR_LENGTH(`admin2`.`nama`), CONCAT_WS('',   `admin2`.`nama`), '') /* AdminID */" => "adminID",
		"IF(    CHAR_LENGTH(`Subjek2`.`subjekNama`), CONCAT_WS('',   `Subjek2`.`subjekNama`), '') /* SubjekID */" => "subjekID"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'subjek' => 'Subjek', 'ditambahOleh' => 'Ditambah Oleh', 'adminID' => 'AdminID', 'subjekID' => 'SubjekID');

	$x->QueryFrom = "`pelajar` LEFT JOIN `Subjek` as Subjek1 ON `Subjek1`.`subjekID`=`pelajar`.`subjek` LEFT JOIN `admin` as admin1 ON `admin1`.`adminID`=`pelajar`.`ditambahOleh` LEFT JOIN `admin` as admin2 ON `admin2`.`adminID`=`pelajar`.`adminID` LEFT JOIN `Subjek` as Subjek2 ON `Subjek2`.`subjekID`=`pelajar`.`subjekID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "pelajar_view.php";
	$x->RedirectAfterInsert = "pelajar_view.php?SelectedID=#ID#";
	$x->TableTitle = "Pelajar";
	$x->TableIcon = "resources/table_icons/group_edit.png";
	$x->PrimaryKey = "`pelajar`.`pelajarID`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Nama", "Umur", "Alamat", "Subjek", "Status Yuran");
	$x->ColFieldName = array('nama', 'umur', 'alamat', 'subjek', 'statusYuran');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/pelajar_templateTV.html';
	$x->SelectedTemplate = 'templates/pelajar_templateTVS.html';
	$x->TemplateDV = 'templates/pelajar_templateDV.html';
	$x->TemplateDVP = 'templates/pelajar_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `pelajar`.`pelajarID`=membership_userrecords.pkValue and membership_userrecords.tableName='pelajar' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `pelajar`.`pelajarID`=membership_userrecords.pkValue and membership_userrecords.tableName='pelajar' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`pelajar`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: pelajar_init
	$render=TRUE;
	if(function_exists('pelajar_init')){
		$args=array();
		$render=pelajar_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: pelajar_header
	$headerCode='';
	if(function_exists('pelajar_header')){
		$args=array();
		$headerCode=pelajar_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: pelajar_footer
	$footerCode='';
	if(function_exists('pelajar_footer')){
		$args=array();
		$footerCode=pelajar_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>